### ISSUE TITLE
Theme generates JavaScript error message

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Unite-Theme#11]
The unite theme generates JavaScript error message "Uncaught TypeError: jQuery(...).ready(...) is not a function" in the browser console as shown in the attached screenshot.
![screenshot 21](https://cloud.githubusercontent.com/assets/11946142/9468274/6396046c-4b5e-11e5-8e65-41f35727fbdf.png)

**Comment by seafoam6** [comment]
I had the same issue.

**Comment by enz513** [comment]
The main.min.js file has a typo (missing ; at the end of line), which is different from the not minimized main.js file.
Add ; at the line of "jQuery(document).ready(...." will solve the problem.

**Comment by AyKuTmania** [comment]
Thanks enz513. But this should be done in main.min.js :+1:

**Comment by enz513** [comment]
This is an duplicate of issue  https://github.com/puikinsh/Unite-Theme/issues/8. The owner will fix this issue in the major update in Nov.
What i provided is only a quick fix in case you can't wait for the official release.

**Comment by FreeWPTP** [comment]
@enz513  Thanks for reporting it here.

I am closing this issue as a duplicate of the following issue.

https://github.com/puikinsh/Unite-Theme/issues/8
