### ISSUE TITLE
How to show the primary menu?

### ISSUE THREAD

**Issue by wesamly** [puikinsh/Unite-Theme#19]
Hello,
I setup a menu, and assigned it to primary location, but it is not showing. I checked code, and I couldn't find a wp_nav_menu for primary location!
When checked your code history, I found that code responsible on showing the menu is removed: https://github.com/puikinsh/Unite-Theme/commit/1cd05d61add71441451b6f5a86466706c91677c9#diff-1c1ae65fe9828eb6d3cee4edacf90018 (at header.php)

How to show the primary menu now?

thank you.

**Comment by puikinsh** [comment]
Hello, 

Thank you for reporting it! I have now fixed it on https://github.com/puikinsh/Unite-Theme/commit/ec42848716f9322a27c0926ec31942e39ca9267a

Let me know if there is anything else.

**Comment by wesamly** [comment]
Cool, thank you.
