### ISSUE TITLE
jQuery issue

### ISSUE THREAD

**Issue by Harsesis** [puikinsh/Unite-Theme#20]
Hi,

I receive a
`TypeError: jQuery(...).ready(...) is not a function`
error on the JS console in main.min.js when using your theme. I've installed it on Wordpress 4.4.2 and all plugins are disabled.

I took a look into the html head and jquery is included properly, I also do not recveive any errors from the bootstrap.min.js which is included before main.min.js and should require jQuery as well?

**Comment by puikinsh** [comment]
@Harsesis

Are you sure that you are using Github version for this theme or one you downloaded from WordPres.org?

**Comment by Harsesis** [comment]
@puikinsh I am using the WordPress version of the theme, I thought it should be the same code base. Are there mayor differences between the versions? I could try to use the Github version instead if that would help!

**Comment by puikinsh** [comment]
It is the same code base but since it takes a lot of time for WordPress.org team to review each update, then Github version might be few fixes/version ahead of that version.

**Comment by FreeWPTP** [comment]
This issue is fixed in the github theme version reported on the following page.

https://github.com/puikinsh/Unite-Theme/issues/8

**Comment by Harsesis** [comment]
Sorry I didn't had time trying this earlier but now I installed the Github version and the issue is resolved! Thank you very much!
