### ISSUE TITLE
Social Icons in v 2.0.1

### ISSUE THREAD

**Issue by Harsesis** [puikinsh/Unite-Theme#22]
Hi,

I updated from the Wordpress version of the theme (v 1.6.1) to the current github version (v 2.0.1) and I couldn't find any options to setup the social icons anymore. Have they been removed in version 2?

**Comment by puikinsh** [comment]
@Harsesis 

This theme now uses WordPress Custom Menus for social icons. 

Create a menu with social links in it an assign it to the right menu location "Social Links" and you should be good go.

**Comment by Harsesis** [comment]
Thank you very much @puikinsh! Looked for that kind of information but couldn't find it! Would be nice to add it as information into the readme or something!

**Comment by puikinsh** [comment]
Sorry about that. it will be referenced in the theme documentation.
