### ISSUE TITLE
Deprecated constructors

### ISSUE THREAD

**Issue by Isk1n** [puikinsh/Unite-Theme#28]
wp_debug complains:

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; unite_popular_posts_widget has a deprecated constructor in …/themes/unite/inc/widgets/popular-posts-widget.php on line 6

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; unite_social_widget has a deprecated constructor in /srv/www/mtbbat.fr/current/web/app/themes/unite/inc/widgets/widget-social.php on line 7

According to http://php.net/manual/en/migration70.deprecated.php , those constructors should be named as
`__construct()`

**Comment by puikinsh** [comment]
Please create a pull request with fixes and will make sure to merge it.

**Comment by puikinsh** [comment]
Resolved on https://github.com/puikinsh/Unite-Theme/pull/33/
