### ISSUE TITLE
Footer to stay at the bottom of a Web page?

### ISSUE THREAD

**Issue by ikramsyakir** [puikinsh/Unite-Theme#31]
On certain pages, where the content doesn’t fill the entire page, the footer does not stick to the bottom (is not pushed down). Is there a way to get the footer to always stick to the bottom, even if the content doesn’t fill the page? Thanks.

![snip_20160611214932](https://cloud.githubusercontent.com/assets/17622728/15995356/a55134ba-314c-11e6-8d96-2e944eb122a6.png)

**Comment by puikinsh** [comment]
Thank you for getting in touch!
For theme related questions please use our [support forum](https://colorlib.com/wp/forums/forum/unite-support/).  Create your own support thread and we will help you from there.

Github is for bug tracking and this isn't a bug. 

Sorry for inconvenience.

**Comment by krxckz** [comment]
I already ask them in support forum at Colorlib.com but no one reply my post. Thank you.
![snip_20160614093839](https://cloud.githubusercontent.com/assets/17622728/16028641/cb3ba170-3213-11e6-908a-3d3d75cae445.png)

**Comment by FreeWPTP** [comment]
I have replied to your following thread so let's resolve it there.

https://colorlib.com/wp/forums/topic/footer-to-stay-at-the-bottom-of-a-web-page/
