### ISSUE TITLE
get_unite_theme_options functioned is added twice in the theme file extras.php

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Unite-Theme#32]
The following commit added the function get_unite_theme_options twice in the theme file extras.php

https://github.com/puikinsh/Unite-Theme/commit/3d99a9e5410c9e1ee114e6530fdae2a2ce57a86f#diff-eb299bdc934d7bcc4d3c4b9c85c0e867

**Comment by puikinsh** [comment]
Resolved on https://github.com/puikinsh/Unite-Theme/pull/33/
