### ISSUE TITLE
2 meta name="description" after installing yoast seo.

### ISSUE THREAD

**Issue by ome999** [puikinsh/Unite-Theme#40]
I am using Yoast SEO Snippet to add Title and Meta description to my posts. On checking page source code i can find to <meta name="description". One is added by yoast seo and another is automatically generated by theme. If excerpt of the specified in post unite theme uses that excerpt for  <meta name="description". Having 2 meta description is not at all a good practice for seo. I have tried every possible way to stop automatic meta name description generation in theme but failed. Please help me to stop automatic generation of meta description. Wordpress url is [https://moviehdapkdownload.com](https://moviehdapkdownload.com). I am using child theme.

**Comment by cristianraiber** [comment]
@ome999 - I just checked your site and it's showing just one meta description tag. Are you referring to the `<meta property="og:description">` tag that's also being shown?

**Comment by hiomkarpatel** [comment]
###

**Comment by hiomkarpatel** [comment]
###

**Comment by cristianraiber** [comment]
@ome999 - This seems a question better fit for the Support forums, which you can reach, here: https://colorlib.com/wp/forums/forum/unite-support/
