### ISSUE TITLE
get_cart_url Issue

### ISSUE THREAD

**Issue by ibininja** [puikinsh/Unite-Theme#5]
Hi
When using woocommerce with (Lockdown WP Admin) plugin a fatal error [ Fatal error: Call to a member function get_cart_url() on a non-object in C:\wamp\www\wordpress\wp-content\themes\unite\inc\extras.php on line 435] appears. When removing the lockdown on admin login  everything is alright (I have tried for the popular plugin (All In One WP Security & Firewall) as well same issue same location. This issue is almost in every theme made for woocommerce. Any directions or thoughts to solving the issue?

**Comment by FreeWPTP** [comment]
@ibininja I have tested on my test site using latest version of WordPress, Unite Theme, WooCommerce & Lockdown WP Admin plugin but couldn't reproduce the issue that you are facing.

Is the issue resolved now with the latest version or is there any specific settings or on specific page does it appear?

Please advise.

**Comment by ibininja** [comment]
I not using unite theme now to be honest been a while. Thank you for reaching out. I will close the issue now though since the issue did not occur on your end..
