### ISSUE TITLE
Options Framework

### ISSUE THREAD

**Issue by nightbook** [puikinsh/Unite-Theme#6]
Hello,

I was following the instructions on the readme and was a bit confused with the Options Framework. It states:
> "This theme relies on Options Framework by WP Theming to provide customization options. Right after you activate Unite, you'll see message on top of your screen, asking you to install Options Framework (required) and CPT Bootstrap Carousel (optional). Make sure you install and activate those plugins."

On theme activation the plugin install only provided the Bootstrap Carousel as an installable, so I went and found and installed the Options Framework plugin which failed and created this error notice:
> Plugin could not be activated because it triggered a fatal error.
> Fatal error: Cannot redeclare optionsframework_init() (previously declared in /home/content/80/12345580/html/freeman/wp-content/themes/unite/inc/admin/options-framework.php:35) in /home/content/80/12345580/html/freeman/wp-content/plugins/options-framework/options-framework.php on line 57

So I've removed the plugin for OF and am going to assume that it's bundled as part of the theme?

Is there something else I should be doing or is the documentation just misleading?

Thank you

**Comment by puikinsh** [comment]
Sorry that part of documentation is dated as Options Framework is now part of theme itself. 

Thank you for pointing that out. Will updated it right away.

**Comment by nightbook** [comment]
Whew thought I was crazy ;) Thanks @puikinsh

**Comment by puikinsh** [comment]
Sorry about that! 

I have now fixed this in theme documentation. 

Thank you for pointing it out!

**Comment by garrett-eclipse** [comment]
Thanks for the quick update @puikinsh

**Comment by nightbook** [comment]
Thanks for the quick update @puikinsh
