### ISSUE TITLE
/inc/js/main.min.js is missing a semicolon

### ISSUE THREAD

**Issue by nickrussler** [puikinsh/Unite-Theme#8]
While main.js does end the [concerned line](https://github.com/puikinsh/Unite-Theme/blob/master/inc/js/main.js#L27) with a semicolon the associated main.min.js [does not](https://github.com/puikinsh/Unite-Theme/blob/master/inc/js/main.min.js#L1). This causes a `Uncaught TypeError: jQuery(...).ready(...) is not a function` for every page visit in chrome for me.

**Comment by pawal** [comment]
It is indeed a problem. Is somebody actually supporting this theme still and fixing issues like this?

**Comment by puikinsh** [comment]
This theme will face a major update in November. 

I seriously injured my hand and had to take several months of from work. Will return in November and will get everything sorted.

**Comment by nickrussler** [comment]
@puikinsh That sounds great. I hope you get better soon!

**Comment by puikinsh** [comment]
Fixed on https://github.com/puikinsh/Unite-Theme/pull/15
