### ISSUE TITLE
On the category page that lists the posts for that category, both the page title and the post title show as h1.

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/Unite-Theme#9]
On the category page that lists the posts for that category, both the page title and the post title show as h1.

See the issue on the following thread.

https://colorlib.com/wp/forums/topic/change-post-title-from-h1-to-h2

**Comment by puikinsh** [comment]
It's now fixed in https://github.com/puikinsh/Unite-Theme/commit/ec5e0016b89ca4bdddffa81d8ea7bb2fa03fd8b2

More changes will be introduced when WP reaches version 4.3.
